name = "my-portfolio-site"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]

[[d1_databases]]
binding = "DB" 
database_name = "portfolio-db" 
database_id = "b7d889c3-71dd-47cc-962c-3ca0033d27c7"
preview_database_id = "b7d889c3-71dd-47cc-962c-3ca0033d27c7"